"""
STOCKSENSE Configuration Package
"""
from config.data_config import (
    PROJECT_ROOT,
    PROCESSED_DATA_DIR,
    RAW_DATA_DIR,
    TRANSACTIONS_PATH,
    INVENTORY_PATH,
    PRODUCTS_PATH,
    STORES_PATH,
    EXTERNAL_FACTORS_PATH,
    MASTER_TABLE_PATH,
    PROFILING_REPORT_CSV,
    PROFILING_REPORT_TXT,
    OUTLIER_REPORT_PATH,
    CLEANING_LOG_PATH,
    QUALITY_REPORT_PATH,
    DATASET_ANALYSIS_REPORT_JSON,
    DATASET_ANALYSIS_REPORT_CSV,
    MODELS_DIR,
    DEMAND_FORECAST_MODEL_DIR,
    STOCKOUT_MODEL_DIR,
    TRAINING_REPORT_PATH,
    REPORTS_DIR,
    DOCS_DIR,
    get_data_paths,
)
